---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 999999999
          http:
    exporters:
      logging:
      otlp:
        endpoint: "ClusterIP-otel-collector-svc:4317" # replace with otel-collector service address
        tls:
          insecure: true
    processors:
      batch:
    extensions:
      health_check: {}
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 999999999
    processors:
      batch:
    extensions:
      health_check: {}
    exporters:
      logging:
      jaeger:
        endpoint: "oteljaeger-collector.otel.svc.cluster.local:14250" # Jaeger service
        tls:
          insecure: true
    service:
      extensions: [health_check]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
